services:
  - type: web
    name: cinesync
    runtime: static
    buildCommand: cd CineSync && npm install && npm run build
    staticPublishPath: CineSync/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html